---
title: "nwfsc_combo_survey"
author: "Joshua Zahner"
date: "1/30/2023"
output: 
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# NWFSC Combo Survey

```{r}
library(nwfscSurvey)
library(tidyverse)

species <- "shortspine thornyhead"
survey.name <- "NWFSC.Combo"
survey.name.path <- str_replace(tolower(survey.name), "[.]", "_")

data.dir <- here::here("data/") # location of data directory
outputs.dir <- here::here("outputs/")

raw.data.dir <- file.path(data.dir, "raw")
catch.fname <- file.path(raw.data.dir, paste0(survey.name.path, "_survey_catch.csv")) # raw survey catch filename
bio.fname <- file.path(raw.data.dir, paste0(survey.name.path, "_survey_bio.csv"))     # raw survey bio filename
out.dir <- file.path(outputs.dir, "surveys", survey.name.path) # send all plot/data outputs here
```

```{r}
dir.create(raw.data.dir, recursive=TRUE)
dir.create(out.dir, recursive=TRUE)
```


```{r, echo=FALSE, message=FALSE, results="hide"}
# Fancy way of automatically using the raw data if its available as a file
# or pulling it from the server and saving it if its not already there.

if(!file.exists(catch.fname) | !file.exists(bio.fname)){
    catch <- PullCatch.fn(Name = species, 
                     SurveyName = survey.name)
                     
    bio   <- PullBio.fn(Name = species, 
                       SurveyName = survey.name)
    
    write.csv(catch, catch.fname)
    write.csv(bio, bio.fname)
}

catch <- read.csv(catch.fname)
bio <- read.csv(bio.fname)

head(catch)
head(bio)
```

```{r}
plot_cpue(
  dir = out.dir, 
  catch = catch
)

plot_bio_patterns(
  dir = out.dir, 
  bio = bio, 
  col_name = "Length_cm")

```

```{r}
# Made a small change to the default wh_plot_proportion() function in nwfscSurvey so
# that the plots are shown in line as well as saved to files.
wh_plot_proportion <- function (data_catch, data_bio, dir = file.path(getwd(), "plots"), 
    bar_width = c("n", "equal")) 
{
    stopifnot(any(c(!missing(data_catch), !missing(data_bio))))
    files_all <- file.path(dir, t(outer(X = c(if (!missing(data_catch)) {
        "presence-absence"
    }, if (!missing(data_bio)) {
        "sex"
    }), Y = paste0("_by_", c("depth", "latitude"), ".png"), FUN = paste0)))
    data <- c(if (!missing(data_catch)) {
        dplyr::mutate(data_catch, the_factor = factor(cpue_kg_km2 <= 
            0, levels = c(FALSE, TRUE), labels = c("Present", 
            "Absent"))) %>% purrr::rerun(.n = 2)
    }, if (!missing(data_bio)) {
        dplyr::mutate(data_bio, the_factor = codify_sex(Sex)) %>% 
            purrr::rerun(.n = 2)
    })
    gg_all <- purrr::pmap(.l = list(pdata = data, x = rep(ggplot2::quos(Depth_m, 
        Latitude_dd), length(data)/2), width = rep(c(50, 1), 
        length(data)/2)), .f = function(pdata, x, width, bar_width) {
        gg <- plot_proportion(data = pdata, column_factor = the_factor, 
            column_bin = !!x, width = width, bar_width = bar_width, 
            boundary = 0)
    }, bar_width = match.arg(bar_width))
    files_out <- purrr::map2_chr(.x = files_all, .y = gg_all, 
        .f = ggplot2::ggsave, height = 7, width = 7)
    return(list(files_out, gg_all))
}

wh_plot_proportion(
  dir = file.path(out.dir, "plots"),
  data_catch = catch,
  data_bio = bio
)
```

```{r}
# Set spatial strata (UPDATE THESE)
strata = CreateStrataDF.fn(
  names          = c("shallow_south", "deep_south", "shallow_cen", "deep_cen", "shallow_north", "deep_north"), 
  depths.shallow = c(55,    500,  55,   500,   55,  500),
  depths.deep    = c(500,  1280,  500,  1280, 500, 1280),
  lats.south     = c(32,     32, 40.5,  40.5,  43,   43),
  lats.north     = c(40.5, 40.5,   43 ,   43,  49, 	 49)
)
```


## Design Based Indices
```{r}
## Calculate design-based index

biomass.idx = Biomass.fn(dir = out.dir, 
                         dat = catch,  
                         strat.df = strata)

PlotBio.fn(
  dir = NULL, # set to `out.dir`to save as file
  dat = biomass.idx,
  scalar = 1000, # convert to kg like csv file
) # produces '_designed_based_index.png'

PlotBioStrata.fn(
  dir = NULL, # set to `out.dir`to save as file
  dat = biomass.idx,
  scalar = 1000, # convert to kg like csv file
) # produces '_designed_based_by_strata_index.png'

```

## Length Compositions

```{r}
n.len.raw <- nrow(bio[!is.na(bio$Length_cm),]) # check is data available

if(n.len.raw > 0){
    n <- GetN.fn(dir = out.dir, 
         dat = bio, 
         type = "length", 
         species = "thorny")
      
    len_bins <- seq(6, 72, 2) # from last assessment (p. 125)
    
    Length_Freq <- SurveyLFs.fn(dir = out.dir, 
                            datL =  bio, 
                            datTows = catch,
                           strat.df = strata,
                            lgthBins = len_bins)
    
    
    PlotFreqData.fn(dir = NULL, # set to `out.dir`to save as file 
                    dat = Length_Freq)
    
    plot_comps(dir = out.dir, data = Length_Freq) # uses version in R/utils/ 
}else{
  print(n.len.raw)
}

```
```{r}

```

## Age Compositions

There is no age data associated with this species and survey, and thus age composition analysis is not possible.
```{r}
n.age.raw <- nrow(bio[!is.na(bio$Age),]) # check is data available

if(n.age.raw > 0){
  
  n <- GetN.fn(dir = out.dir,
         dat = bio,
         type = "age",
         species = "thorny")

  age_bins <- 1:22 # arbitrarily set right now as not used in previous assessment
  
  Ages <- SurveyAFs.fn(dir = out.dir,
                       datA = bio,
                       datTows = catch,
                       strat.df = strata,
                       ageBins = age_bins,
                       nSamps = n)
  
  PlotFreqData.fn(
    dir = out.dir,
    dat = Ages
  )
  
  plot_comps(
    dir = out.dir,
    data = Ages
  ) # uses the version in R/utils/
  
}else{
  print(n.age.raw)
}

```

## Conditional Age-at-Length
There are no ages associated with this species and survey, so CAAL analyses are not possible.
```{r}
if(n.age.raw > 0){
  caal <- SurveyAgeAtLen.fn(dir = out.dir,
                          datAL = bio,
                          datTows = catch,
                          strat.df = strata,
                          lgthBins = len_bins,
                          ageBins = age_bins) 
}
```

