---
title: "Catch only projection for shortspine thornyhead"
author: "Kiva L. Oken" 
affiliation: 'NOAA Fisheries Northwest Fisheries Science Center, 2725 Montlake Blvd E, Seattle, WA 98112'
date: today
format: 
  pdf:
    template: catch_only_projection_template.tex
params:
  species: "shortspine thornyhead"
  assess_year: 2023
  current_year: 2025
  final_proj_year: 2036
  category: 2
  sigma: 1
  p_star: 0.45
  spawn_output_decimals: 2
  dir_original: "cop3"
  dir_new: "spex_27_28"
  spawn_output_units: "(billions of eggs)"
---


```{r}
#| label: parameters
#| echo: false
#| warning: false
#| message: false
species <- params$species
Species <- stringr::str_to_sentence(params$species)
assess_year <- params$assess_year
current_year <- params$current_year
final_proj_year <- params$final_proj_year
category <- params$category
sigma <- params$sigma
p_star <- params$p_star
spawn_output_decimals <- params$spawn_output_decimals

# original model
model_original <- r4ss::SS_output(
    dir = params$dir_original,
    verbose = FALSE,
    printstats = FALSE,
    hidewarn = TRUE
)

# catch-only projection
model <- r4ss::SS_output(
    dir = params$dir_new, # this is the directory where I ran the standard Catch-only projection model
    verbose = FALSE,
    printstats = FALSE,
    hidewarn = TRUE
)

table_caption <- glue::glue("Adopted 2025 catch-only update projection and projection with updated HCR for 2027 and 2028. Table includes OFLs (mt), buffer, ABCs (mt), actual & assumed catch (mt), ACLs (mt), spawning output {params$spawn_output_units}, and stock status (fraction of unfished spawning output) given the removals. The gray shading indicates values associated with the original catch-only update. For 2029 and beyond, the default HCR with 40-10 rule and P* of {params$pstar} is assumed")
```

This document details new projections for `r species` based on the 2026 catch-only projection adopted by the Council (G.8 Attachment 2, Table 3 from the September, 2025 Council meeting). The specifications through 2026 remain unchanged. The ABCs and ACLs for 2027 and 2028 are all assumed to be 902 mt.

```{r}
#| label: calc-table
#| echo: false
#| warning: false
#| message: false

# define ranges of years to get values
all_years <- assess_year:final_proj_year
proj_years <- (current_year + 1):final_proj_year
catch_years <- assess_year:(current_year)
diff_years <- current_year - assess_year

# function to get model outputs
catch_only_projection_table <- function(model, all_years, proj_years, catch_years) {
    # get realized catch from model output
    catch <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("ForeCatch_", catch_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            Catch = Value
        )
    ofl <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("OFLCatch_", proj_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            OFL = Value
        )
    acl <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("ForeCatch_", proj_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            ACL = Value
        )
    sb <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("SSB_", all_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            SB = Value
        )
    status <- model$derived_quants |>
        dplyr::filter(Label %in% paste0("Bratio_", all_years)) |>
        dplyr::reframe(
            Year = stringr::str_extract(Label, "\\d+") |> as.numeric(),
            status = round(Value, 3)
        )

    # get buffer from PEPtools function
    Buffer <- PEPtools::get_buffer(
        years = all_years, sigma = sigma, pstar = p_star,
        verbose = FALSE
    ) |>
        dplyr::rename(Year = year, Buffer = buffer) |>
        dplyr::filter(Year %in% proj_years)

    # combine all the tables above (joined by year)
    table <- purrr::reduce(
        list(ofl, Buffer, acl, sb, status, catch),
        ~ dplyr::full_join(.x, .y, by = "Year")
    ) |>
        dplyr::arrange(Year) |>
        dplyr::relocate(Catch, .after = Year) |>
        dplyr::mutate(
            Buffer_from_ratio = dplyr::case_when(
                status >= model$btarg ~ round(ACL / OFL, 3),
                .default = NA # ratio doesn't work for years with 40-10 adjustment
            ),
            .after = Buffer
        ) |>
        dplyr::mutate(
            ABC = Buffer * OFL,
            .after = Buffer_from_ratio
        ) |>
        dplyr::rename(
            `Actual & Assumed Removals` = Catch,
            `Stock Status` = status,
            `Spawning Output` = SB,
        )
}

combine_tables <- function(table1, table2) {
    dplyr::full_join(
        table1,
        table2,
        by = "Year"
    ) |>
        dplyr::select(
            c(
                "Year",
                "OFL (yyyy)", "OFL",
                "Buffer",
                "ABC (yyyy)", "ABC",
                "Actual & Assumed Removals (yyyy)", "Actual & Assumed Removals",
                "ACL (yyyy)", "ACL",
                "Spawning Output", "Stock Status (yyyy)", "Stock Status"
            )
        ) |>
        dplyr::rename_with(.fn = function(x) {
            gsub("yyyy", 'COU', x)
        })
}

# function to apply gt formatting to the table
format_table <- function(table) {
    table |>
        gt::gt() |>
        gt::fmt_number(
            columns = tidyselect::starts_with("Actual") | tidyselect::starts_with("OFL") | tidyselect::starts_with("ABC") | tidyselect::starts_with("ACL"),
            decimals = 0
        ) |>
        gt::fmt_number(
            columns = tidyselect::contains("Spawning"),
            decimals = spawn_output_decimals
        ) |>
        gt::tab_options(
            table.font.size = 11, # reduced font size
            latex.use_longtable = TRUE
        ) |>
        gt::sub_missing(
            columns = tidyselect::everything(),
            missing_text = "---"
        ) |>
        gt::cols_align(
            align = "center"
        ) |>
        gt::cols_width(
            everything() ~ px(65)
        ) |>
        gt::data_color(
            columns = tidyselect::contains('COU'),
            palette = "gray90",
            na_color = "gray90"
        ) |>
        gt::as_latex()
}

table <- catch_only_projection_table(model,
    all_years = all_years, proj_years = proj_years, catch_years = catch_years
)
table_original <- catch_only_projection_table(model_original,
    all_years = all_years, proj_years = proj_years, catch_years = catch_years
)

```

```{r}
#| label: warning-about-buffer
#| echo: false
#| warning: true
#| message: true

if (any(abs(table$Buffer_from_ratio - table$Buffer) > 0.01, na.rm = TRUE)) {
    cli::cli_alert_warning("ACL / OFL differs from buffer calculated by PEPtools::get_buffer() by more than 0.01 for years with status > target. See values below.")
    print(table)
} else {
    table <- dplyr::select(table, -Buffer_from_ratio)
}

if (any(abs(table_original$Buffer_from_ratio - table_original$Buffer) > 0.01, na.rm = TRUE)) {
    cli::cli_alert_warning("ACL / OFL differs from buffer calculated by PEPtools::get_buffer() by more than 0.01 for years with status > target. See values below.")
    print(table_original)
} else {
    table_original <- dplyr::select(table_original, -"Buffer_from_ratio")
}

table_original <- table_original |>
    dplyr::select(-Buffer, -"Spawning Output") |>
    dplyr::rename_with(~ paste(.x, "(yyyy)"), .cols = -Year)
# combine the two tables
wide_table3 <- combine_tables(table, table_original)

# move 2026 ACL to assumed catch column
wide_table3$"Actual & Assumed Removals"[wide_table3$Year == 2026] <- 
  wide_table3$ACL[wide_table3$Year == 2026]
wide_table3$"Actual & Assumed Removals (COU)"[wide_table3$Year == 2026] <- 
  wide_table3$ACL[wide_table3$Year == 2026]

# calculated 2026 ABC from OFL
wide_table3$ABC[wide_table3$Year == 2026] <- 
  wide_table3$OFL[wide_table3$Year == 2026] * 
  PEPtools::get_buffer(2023:2026, sigma = 0.5, pstar = 0.45, verbose = FALSE)[4, 'buffer']
wide_table3$`ABC (COU)`[wide_table3$Year == 2026] <- 
  wide_table3$`OFL (COU)`[wide_table3$Year == 2026] * 
  PEPtools::get_buffer(2023:2026, sigma = 0.5, pstar = 0.45, verbose = FALSE)[4, 'buffer']

# calculate 2026 ACL from ABC
# get 2026 stock status for use in 40-10 or 25-5 rule
D <- wide_table3$"Stock Status"[wide_table3$Year == 2026]
#
adj <- 1.0
# 40-10 rule for most species
if (D < model$btarg & model$btarg == 0.40) {
  adj <- (4/3)*(D-0.1)/D
}
# 25-5 rule for flatfish
if (D < model$btarg & model$btarg == 0.25) {
  adj <- (25/20)*(D-0.05)/D
}
# calculate ACL from adjustment * OFL
wide_table3$ACL[wide_table3$Year == 2026] <- 
  adj * wide_table3$ABC[wide_table3$Year == 2026] #ABC
# don't need to redo the calculations with and without COU, they are identical through 2026
wide_table3$`ACL (COU)`[wide_table3$Year == 2026] <- 
  adj * wide_table3$ABC[wide_table3$Year == 2026] #ABC

wide_table3$ABC[wide_table3$Year %in% 2027:2028] <- wide_table3$ACL[wide_table3$Year %in% 2027:2028]

wide_table3$Buffer[wide_table3$Year == 2026] <- PEPtools::get_buffer(2023:2026, sigma = 0.5, pstar = 0.45, verbose = FALSE)[4, 'buffer']
```

::: {.landscape}

```{r}
#| label: tbl-proj
#| echo: false
#| warning: false
#| message: false
#| eval: true
#| tbl-cap: "Adopted 2025 catch-only update projection and projection with updated HCR for 2027 and 2028. Table includes OFLs (mt), buffer, ABCs (mt), actual & assumed catch (mt), ACLs (mt), spawning output (billions of eggs), and stock status (fraction of unfished spawning output) given the removals. The gray shading indicates values associated with the adopted catch-only update (G.8 Attachment 2, Table 3 from the September, 2025 Council meeting). For 2029 and beyond, the default HCR with 40-10 rule and P* of 0.45 is assumed"
format_table(wide_table3)
```
