# Data

Data comprise the foundational components of stock assessment models.
The decision to include or exclude particular data sources in an assessment model depends on many factors.
These factors often include, but are not limited to,
the way in which data were collected (e.g., measurement method and consistency);
the spatial and temporal coverage of the data;
the quantity of data available per desired sampling unit;
the representativeness of the data to inform the modeled processes of importance;
timing of when the data were provided;
limitations imposed by the Terms of Reference; and
the presence of an avenue for the inclusion of the data in the assessment model.
Attributes associated with a data source can change through time,
as can the applicability of the data source when different modeling approaches are explored (e.g., stock structure or time-varying processes).
Therefore, the specific data sources included or excluded from this assessment should not necessarily constrain the selection of data sources applicable to future stock assessments for `r spp`.
Even if a data source is not directly used in the stock assessment they can provide valuable insights into biology, fishery behavior, or localized dynamics.

Data from a wide range of programs were available for possible inclusion in the current assessment model.
Descriptions of each data source included in the model (Figure \@ref(fig:data-plot)) and sources that were explored but not included in the base model are provided below.
Data that were excluded from the base model were explicitly explored during the development of this stock assessment or have not changed since their past exploration in a previous `r spp` stock assessment.
In some cases, the inclusion of excluded data sources were explored through sensitivity analyses (see Section \@ref(assessment-model)).

An overview of the data sources available for each combination of fleet and year is provided in *_Figure XXX._* 


## Biology

### Natural mortality and longevity 

### Length-weight relationship 

### Length-at-age

### Maturity 

### Fecundity 

## Catch History 

PacFIN data from 1981-present was used to estimate landings in the North (Oregon and Washington) and South (California) by gear type (Trawl and Non-Trawl) *_(Figure XX)._* All landings reported for the Shortspine thornyhead and nominal Shortspine thornyhead categories were considered Shortspine thornyheads, whereas landings categorized as unidentified thornyheads were split between Longspine thornyhead and Shortspine thornyhead by the ratio of identified longspine and shortspine landings for each year-state-gear combination. The values of this ratio for each state and gear-type from 1981-2023 are shown in *_Figure XX._* 

Catches prior to 1981 are based on historical reconstructions provided by the respective states and a reconstruction of foreign fleet catch. Oregon landings for 1892-1986 are provided by ODFW and outlined in *Karnowski, et al. (2014).* Shortspine thornyhead landings are not present in the PacFIN data for Oregon for the years 1981-1986 and the state reconstruction is used for this period instead. Washington landings for 1954-1980 are provided by WDFW. Landings prior to the beginning of this data are assumed to be zero. California landings are provided by CDFW and SWFSC, and consist of California commercial data for 1969-1980, and a catch reconstruction documented by *Ralston, et al. (2010)* for 1934-1968. As in the two previous assessments, catch data from *Rodgers (2003)* is used to account for catches by foreign fleets during the years 1966-1976. Foreign catch in the Monterey and Eureka INPFC areas is attributed to the Southern Trawl fleet, while foreign catch in Columbia and Vancouver areas is attributed to the Northern Trawl fleet, as was the case in the 2013 assessment.

For historical catches prior to 1981, all Shortspine thornyhead, nominal shortspine, and unidentified thornyhead landings in the state catch reconstructions are considered Shortspine thornyhead. Neither California reconstructions prior to 1978, nor the *Karnowski et al. (2014)* reconstruction for Oregon, distinguish between Shortspine and Longspine thornyhead species. It is possible that assigning all thornyhead landings to shortspine overestimates shortspine landings, however, the overwhelming majority of thornyhead landings were shortspine until the late 1980s when vessels began to move into deeper waters and a distinct fishery targeting Longspine thornyhead developed *(Hamel 2005; Karnowski, et al. 2014)*. 

This treatment of unassigned thornyhead landings differs from the 2005 and 2013 assessments. The 2005 assessment did not have access to the historical reconstructions used here, and instead imputed Shortspine landings as 30% of annual Sablefish landings for the years 1901-1961. The 2013 assessment used the same imputed values as the 2005 assessment, but also conducted a sensitivity analysis in which all unassigned thornyheads in historical catch were considered Shortspine thornyhead. Stock abundance estimates were found to be largely insensitive to which reconstructions were used *(Taylor and Stephens 2013)*. The imputed historical values used for the 2005 and 2013 assessments will continue to be included as a sensitivity analysis here. Landings after 1961 remain very similar to the landings used in the 2013 assessment *_(Figure XX)_*. 


## Discards and retention

Discards were informed by four data sources covering three different periods. Data sets included, 1) *Pikitch et al.* Discard and Mesh Studies, used to estimate both discard rates and length composition of the northern trawl fleet between 1985 and 1987 *(J. R. Wallace, pers. comm.)*, 2) the *Enhanced Data Collection Project (EDCP)* covering 1995-1999, which only informed discard rates of the northern trawl fleet, 3) the *West Coast Groundfish Observer Program (WCGOP)*, which provided discard rates, length composition, and individual average weight for years between 2002 and 2021 for all fleets, and 4) the *Groundfish Expanded Mortality Multiyear (GEMM)* dataset, covering the same period and completing the *WCGOP* with catch-share participation information and estimates of discard survival rates.

While the estimates from the first two data sets were directly integrated into the model, fleet discard rates after 2011 were available separately for catch-share and non-catch-share programs. Final fleet-specific discard rates were thus computed as the average *WCGOP* discard rate weighted by the relative proportion of total landings belonging to the catch-share and non-catch-share, respectively. *_(Figure XX)_*. Regardless of the type of data, all estimates derived from these data sets had associated uncertainty accounting for the variability observed within the sample of hauls and fishing trips of each fleet. WCGOP-derived discard rates are an exception as, after the catch share program was initiated in 2011, 100% of hauls from catch share fleets were observed., while non-catch share vessels were only partially covered *_(cite)_*.

The discard data sources were the same as those used in the 2013 assessment. The main improvements are the increased representativity of all 4 fleets (11 more years) and more accurate estimates of discard rates from EDCP that were not ready at the time of the previous assessment. Last, some errors in the previous assessment were corrected regarding the weight units considered for the average individual weight (WCGOP provides weight as pounds and not as kg).

## Fishery Length Compositions 

Commercial fishery length-composition data were obtained from PacFIN for 1978-2023. Due to variations in sampling effort and because the number of fish sampled by port samplers is not proportional to the amount of landed catch in each trip, the observed length data were expanded using the following algorithm using the PacFINUtilities package in R:

*Length data were acquired at the trip level by sex, year and state.
*The raw numbers in each trip were scaled by a per-trip expansion factor calculated by dividing
the total weight of trip landings by the total weight of the species sampled.
*A per-year, per-state expansion factor was computed by dividing the total weight of state
landings by the total weight of the species sampled for length in the state.
*The per-trip expanded numbers were multiplied by the per-state expansion factor and summed to provide the coastwide length-frequency distributions by year.

Only randomly collected samples were used. The sample sizes associated with the length compositions from the fishing fleets are shown in *_Table X (landings)_* and *_Table X (discards)_*. Length samples from the Trawl North fleet in the years 1980, 1994, and 1995 showed a very different pattern than the surrounding years. The effective sample sizes for these years were substantially lower than other years (Neff < 15), so the observed differences are likely due to non-representative sampling. Therefore all years with effective sample sizes of less than 15 were not included in the base model. The 2013 assessment found that taking these undersampled years out made very little difference in model results. 

Input sample sizes (Ninput) for fishery length frequency distributions by year were calculated as a function of the number of trips and number of fish via the Stewart Method *(Stewart, pers.com)*: 

ADD EQUATIONS HERE 

The method is based on analysis of the input and model-derived effective sample sizes from west coast groundfish stock assessments. A piece-wise linear regression was used to estimate the increase in effective sample size per sample based on fish-per-sample and the maximum effective sample size for large numbers of individual fish.

All length data from commercial fisheries included in the model with sexes combined. This avoids the possibility of bias due to difficulty in sex determination of thornyheads.

## Age Compositions 

No age composition data was used for this assessment because thornyheads have proven very difficult to age *(P. MacDonald, pers. comm.)*.  Even in directed studies such as those done by *Kline (1996) and Butler et al. (1995)*, there are large inter-reader differences, and a second reading by the same ager can produce a markedly different result. *Kline (1996)* reported only about 60% of the multiple reads were within 5 years of each other, and inter-reader differences were as large as 24 years for a sample of 50 otoliths. No production ageing of thornyheads is undertaken at this time for the west coast, although shortspine thornyhead otoliths are routinely collected in the NWFSC trawl survey.


## NMFS Surveys 

### Triennial Survey 

### AFSC and NWFSC Slope Surveys 

### West Coast Groundfish Bottom Trawl Survey 

### Survey Stratification 

### Design-based Indices of Abundance 

### Geostatisitical Model-based Indices of Abundance 

### Frequency of Occurrence 

The frequency of occurrence of shortspine and longspine thornyheads in trawl surveys remains extremely high. 91% of the tows in the NWFSC Combo Survey below 500 m have at least one shortspine thornyhead in the catch (and 96% for longspine thornyhead), similar to the 2013 assessment. 


### Length Composition Data 

### Sample and Hault Information

The number of survey hauls and shortspine thornyheads sampled available for this assessment is described in *_Table XXX._*


## Changes in data from the 2013 assessment 

Most of the data used in the previous assessment has been newly extracted and processed, including length compositions from each fishing fleet and survey, indices of abundance derived from new geostatistical models of survey data, discard rates from both the 1980s Pikitch study and the current *West Coast Groundfish Observer Program (WCGOP)*, and the time series of catch from 1900-2023.

New data for this assessment include the geostatistical model-based indices of abundance for the four fisheries independent surveys, the histological maturity samples from the *WCGBT* survey, and the historical state catch reconstructions. Previous assessments have treated the AFSC Triennial Shelf Survey as two separate indices of abundance separated by the 366m depth contour, but the transition to using geostatistical model-based indices have rendered this separation unnecessary by implicitly accounting for changes in depth sampling within the model. State-level historical reconstructions also replace previous analyses that imputed historical Shortspine thornyhead catch as a fixed proportion of Sablefish catch.


## Environmental and Ecological Data 
No ecological or environmental information was used in this assessment. 



