## Model Structure and Assumptions

### Model Changes from the Last Assessment
The most notable changes from the previous assessment, conducted in 2013, include significant modifications to the fleet and survey structure, and major changes to the maturity and fecundity relationships that underlie the model’s biological assumptions. 

The 2013 assessment consisted of four fisheries fleets, and used information from four (nominally five) scientific surveys, while the new assessment uses a condensed structure consisting of just three fisheries fleets and only two (nominally three) surveys (see Section 3.2.3 for more details). 

This assessment assumes a new fecundity relationship, in which fecundity increases with body size, as well as a new maturity relationship, in which fish mature at much larger sizes and thus older ages, than were assumed in the 2013 assessment. Further details on the fecundity and maturity relationships can be found in Section 2.3.2. A sensitivity analysis was performed to determine the effect of different maturity assumptions on the final model output.

### Modeling Platform and Bridging Analysis
This new assessment, including all exploratory models, profiles, and related analyses, was performed using Stock Synthesis Version 3.30.21 [@methot_stock_2013; @ss_manual_2020). The majority of analyses were performed using multiple recent versions of R [@r_core_2021], and relied heavily on the `r4ss` R package [@r4ss] among others. The assessment model was developed and tested across multiple operating systems, including recent versions of Windows and macOS.

The process of bridging to a new model occurred in two steps. The initial bridging phase focused on the conversion from version SS-V3.24o to version SS-V3.30.21 using the same data and model assumptions used in the 2013 assessment. Two models were built during this first step: an initial model which fixed parameter values at the values estimated in the 2013 assessment (“2013 Model SS V3.30.21 Fixed Params”) and a second model which estimated  all parameters as assumed in the 2013 assessment (“2013 Model SS V3.30.21”). 

The subsequent bridging exercise involved updating the model (“2013 Model SS V3.30.21”) with the addition of new and reprocessed data through 2023 as well as updating biological parameters (growth, maturity, fecundity, and mortality parameters - see Section 2.3 for more details). Additional data include new catch, discard, survey indices, length-composition, and mean body weight (for discards only) data. The contribution of each data component and parameter update to the changes in the model outcome were analyzed by adding data and updating parameters in a linear piecewise fashion.

While there were no discernible changes between the 2013 assessment and the “2013 Model SS V3.30.21 Fixed Params" model, differences were observed in the estimated spawning biomass, recruitment (age-0 fish), and fraction of unfished time series between these two models and the “2013 Model SS V3.30.21” model (marginally smaller spawning biomass and recruitment along with a smaller depletion level from the end 1970s onward; Figure \ref{fig:bridge_bratio}). The source of these changes can be attributed to differences in the way of analytically computing survey catchability (“floatQ”  approach, see Section 3.2.4.3) between the two versions of Stock Synthesis. 

Inclusion of new data and updated parameters resulted in a series of changes to model outcomes (Figure \ref{fig:bridge_spawnout_data}, Figure \ref{fig:bridge_bratio_data}). While the update of both growth and maturity parameters led to variation of spawning biomass in the range of the uncertainty previously observed (models "Updated Growth" and "Updated Maturity", respectively), the one notable change in the estimates of spawning biomass occurs with the update of fecundity parameters (model "Updated Fecundity") which resulted in a strong downward revision of the spawning biomass time series. This major change can be explained by the use of a new length-based fecundity relationship which was not considered in the previous assessment (see Section 1.1.1 for more information).

### Model Structure
Similar to the 2013 assessment, the 2023 assessment model is a two-sex, length-based age-structured model that estimates population dynamics from 1901 onwards. The model assumes a steady equilibrium state with no fishing prior to the start year of the model (1901) and considers a spatially homogeneous unit stock in the waters off the U.S. West Coast.

Commercial fisheries landings were divided into three distinct fisheries fleets: a northern trawl fleet (hereinafter referred to as North Trawl) operating off the coasts of Oregon and Washington (including catch from the at-sea Pacific whiting fishery), a southern trawl fleet (hereinafter referred to as South Trawl) operating off the coast of California, and a coastwide non-trawl fleet (hereinafter referred to as Non-trawl).

Data from two fisheries-independent scientific surveys were used in this model: the \gls{s-tri} from 1980-2004, and the more recent \gls{s-wcgbt} from 2003-2022. The \gls{s-tri} length compositions were further divided into an early (pre-1995) and late period (post-1995) survey to account for changes in selectivity due to the change in depth-sampling that occurred during the 1995 season. These two periods for the \gls{s-tri} were treated as separate surveys in the model. The \gls{s-tri} abundance index timeseries is treated as a single timeseries spanning 1980-2004. The contribution of each new data component to the changes in the assessment outcome was analyzed by adding data in a linear piecewise way in order to understand how each change contributed to the model outcome. 


### Model Parameters
There are 197 estimated parameters in this assessment. The log of unfished recruitment, $\ln(R_0)$, controls the overall scale of the population, while annual deviations in recruitment about the assumed stock-recruit relationship (135 parameters) allow for additional uncertainty in the population trajectory and tracking of recent recruitment events. Selectivity and retention parameters (59 parameters) for three fisheries fleets and three scientific surveys allow for estimation of annual length compositions and discards rates. Two catchability parameters are analytically computed from the data, and one additional parameter, representing additional variability in the early \gls{s-tri}, is directly estimated by the model. A variety of selectivity and retention blocks are utilized to improve fits to the length composition and discard rate information (Figure \ref{fig:timeblocks})

#### Growth, Maturity, Fecundity, Mortality, and Recruitment
Growth, maturity, and fecundity parameters were fixed at values determined by external analyses (see **Section 2.3** for more information). Due to a lack of aging data, growth could not be modeled internally by the assessment, though, like in the 2005 and 2013 models, there is no systematic misfit to the data suggesting that the externally derived growth curves were misspecified. Sensitivity analyses were performed to determine the overall effect of different assumptions regarding growth and maturity. 

For this assessment, natural mortality ($M$) was fixed at a value of 0.04, as such a value provided better fits to the data and literature information implies that the maximum age of `r spp` could be well over 100 years. A likelihood profile exploring alternative natural mortality values was also conducted (Figure \ref{fig:M_prof}). In the 2013 assessment, M was fixed at 0.0505 @taylor_stephens_2013, however, because `r spp` are difficult to age, aging error may bias age to be lower and they may live longer than those caught in surveys or fishing fleets, likely at deeper depths. Recent `r spp` assessments in Alaska and British Columbia used much lower M, as low as 0.03, in their models [@starr_haigh_2017; @echave_etal_2022].


As in the previous `r spp` assessment, a Beverton-Holt stock recruitment relationship was assumed. Unlike the 2013 assessment, where steepness was fixed at a value of 0.60, this assessment fixed steepness at 0.72, as recommended by @thorson_steepness_2019. A likelihood profile exploring alternative steepness parameters was conducted and the model results were found to be largely insensitive to the assumed value (Figure \ref{fig:h_spawnout}).

The overall scale of the population is estimated through the log of the initial recruitment parameter ($R_0$). Recruitment deviations were additionally estimated for the years 1901-2022. Recruitment bias adjustments were phased in beginning in 1950, and were adjusted by a factor of 0.30 in the years 1982-2018 [@taylor_hiding_2013]. The $\sigma_R$ parameter which controls the variability in recruitment deviations was fixed at 0.5 as in the previous assessment. Past assessments performed likelihood profiles over $\sigma_R$, finding the model results to be relatively insensitive to its value, and thus further profiles over the parameter were not conducted here.

#### Selectivity and Retention
Gear selectivity parameters used in this assessment were specified as a function of size with the additional assumption that age 0 fish were not selected, regardless of their size. Separate size-based selectivity curves were fitted to each fishery fleet and survey. 

The selectivity curves for all fisheries and surveys were allowed to be dome-shaped and modeled with double-normal selectivity. The double-normal selectivity curve parameterization has six parameters, including: (1) peak, the length at which individuals are first fully selected, (2) width of the selectivity plateau, (3) width of the ascending part of the curve, (4) width of the descending part of the curve, (5) starting selectivity, and (6) final selectivity. Parameters 5 and 6 were not estimated and fixed at 0.0. The 2013 model allowed for all selectivity parameters to be estimated, regardless of whether one or more were estimated to be on the parameter bound. This model fixed parameter 2 (the plateau width) to the value of -15 for the North Trawl fleet to alleviate them hitting the lower parameter bound. Though exploratory models run with the plateau width on its lower bound still converged, fixing the parameter had negligible impact on the fits to the length composition data for this fleet. Sex-specific selectivity curves were fit to the \gls{s-wcgbt} and \gls{s-tri} length composition data.

As a new addition to this assessment, time-varying selectivity curves were estimated for the North and South trawl fleets. Three time blocks accounted for potential structural changes in these fisheries: (1) the historical period from 1901—2002, (2) 2003—2010, for the implementation of rockfish conservation areas, and (3) 2011 for the start of the \gls{ifq} program through the present (Figure \ref{fig:timeblocks}; Figure \ref{fig:diagram}). 

Retention curves are defined as a logistic function of size. These are controlled by four parameters: (1) inflection, (2) slope, (3) asymptotic retention, and (4) male offset to inflection. Male offset to retention was fixed at 0 (i.e., no male offset was applied). The parameters for inflection and asymptotic retention (asymptotic retention was estimated for North Trawl and Non-Trawl, and fixed for South Trawl as the estimate was hitting the upper parameter bound) were modeled as time-varying quantities via the use of time blocks. Time blocks were expanded from the 2013 assessment. Both North Trawl and South Trawl fleets were broken into six time blocks, with slight variation between fleets: (1) 1901–1988, (2) 1989—2006, (3) 2007–2010, (4) 2011–2014 for North Trawl and 2011—2016 for South Trawl, (5) 2015—2019 for North Trawl and 2017—2019 for South Trawl, and finally (6) 2020—2022 for both trawl fleets (Figure \ref{fig:diagram}; Figure \ref{fig:retblocks}). Notably, the sequence of shorter time blocks starting after 2006 noticeably improved fits to the lower discards rates seen in the mid-2010s; in a similar way, transition between the first and second time blocks improved the fit to discard rates from the Pikitch study. Additionally, a short, 3-year, time block for the years 2020 and 2022 was also included, as discard rates were noticeably higher in those years than in previous. After merging the two Non-Trawl fleets previously considered in the 2013, the reasons that justified the time blocks used in the 2013 assessment were not pertinent anymore and we decided not to represent time-varying retention for this fleet.


#### Catchability
Catchability coefficients (q) were calculated for each of the two survey abundance time series. Like the 2013 model, catchability was analytically for each survey using the Stock Synthesis “floatQ” option, though the exact analytical computation has changed from what was used in 2013 [@ss_manual_2020]. 

This model depends on the assumptions that thornyheads are long-lived, slow-growing, and relatively sedentary groundfish. They are assumed to represent a single stock within the area considered for this assessment. If the assumptions about growth, natural mortality, or stock structure turn out to be far from the true life history and ecology of `r spp`s, this assessment will be highly inaccurate.
