## Base Model Results


### Parameter Estimates
A complete set of parameter estimates are available in **Table XX**.

#### Recruitment
The model estimated 135 annual recruitment deviations (1901-2034) as well as the log of unfished recruitment LN(R0). Unfished recruitment was estimated to be ~11,000,000 annual age-0 recruits (LN(R0) = 9.34) while annual log deviations were generally estimated between -0.5 and 0.5 (**Figure XX; Table XX**). Deviations in 2003 and 2007 were estimated to be substantially larger than other years. As in the 2013 assessment, uncertainty in the scale of annual deviations was substantially larger than the variation between the deviations. Recruitment bias adjustments were performed following the advice of @methot_adjusting_2011.

#### Selectivity and Retention
Selectivity curves for all three fisheries fleets and the three scientific surveys were estimated as dome-shaped. 

The early- and late-period Triennial survey possessed the highest degree of dome-shape, with peak selectivity occurring at relatively small length (~26 cm, and ~22 cm respectively), before quickly declining. This shape is consistent with the design of the survey which focused its sampling on the relatively shallow shelf, where younger, smaller, `r spp` live before migrating to deeper waters as they age and mature . and tThere was little difference in the estimated selectivity curves between male and female fish. Meanwhile, the WCGBTS was estimated to have a wide plateau (beginning at ~30cm) over which the species is fully selected for, including the lengths over which the species spends the bulk of its lifespan. This indicates that the WCGBTS is sampling a large proportion of the stock, and that annual length composition data from the survey is likely a good representation of the true distribution of lengths in the population. 

The North Trawl fleet was estimated to have a dome-shaped curve with a small plateau around 28 cm in length, and a long tail that spanned nearly the entire range of observed lengths. The South Trawl fleet was estimated to have a very large selectivity plateau (beginning at ~30cm, ranging from 30-55cm, with very steep ascending and descending limbs. Finally the Non-Trawl fleet was estimated to have a relatively small plateau beginning at a much higher length than any other fleet or survey (~45 cm). This fits with the assumption that the hook and line gear that is primarily used by the Non-Trawl fleet would not select small `r spp`. 

### Fits to the Data

#### Abundance Indices
The base model reasonably fit the available index data with the exception of the most recent two years of the WCGBTS. The fit to the Triennial survey was relatively flat across the entire timeseries (1980-2004; **Figure XX**). An extra parameter was used to estimate additional variance beyond that estimated by the geostatistical model for this survey. The model fit to the \gls{s-wcgbt} indices appropriately captured the lack of trend in the early and middle portions of the timeseries, but struggled to accurately capture the recent increase in abundance displayed by the indices (**Figure XX**). The model fit for this survey fails to fall within the estimated confidence interval for the 2021 and 2022 indices. This could be, in part, due to the lack of index data from 2020 (surveys were not conducted due to the ongoing COVID-19 pandemic), which may have helped the model more accurately capture the increase.

#### Fishery Discard Rates
The model reasonably fit the discard rates for all three fisheries fleets. The three timeblocks, carried over and extended where necessary from the 2013 model, allowed for the declining trend in discards for the North Trawl fleet to be adequately captured, however, there is a period from 2015-2018 where discards rates for the North Trawl fleet are exceptionally low, that the model fails to fully capture (**Figure XX**). Discards rates in the Southern Trawl fleet are well fit 2006-2014, before and after which the model systematically underestimates the observed discards rates (**Figure XX**). The discard rates for the coastwide Non-Trawl fleet are exceptionally well fit by the model, and there is no evidence that time blocking is necessary for this fleet (**Figure XX**).

#### Fishery Length Compositions
The base model fit the fishery and discard length compositions reasonably well in aggregate (**Figure XX**), though there was significant annual variability in the quality fit, often due to difference in effective sample sizes. The Southern Trawl and Non-Trawl fleets were exceptionally well fit by the model, while the model fit to the length compositions from the Northern Trawl fleet underestimated the scale of the peak of the distribution. This type of misfit was similarly observed in the model fits on an annual basis, with all years 2018-2022 displaying a similar underestimation of either the location or scale of the peak of the distribution (**Figure XX**). The exact causes of this under-estimation remain unknown at this time, but could be due to subtle changes in selectivity or availability. The effect of including time-varying selectivity was assessed in a sensitivity analysis (**see 3.4.4.2 for details**). 

Trawl discards length compositions were well fit by the model in both the north and south regions, while the model struggled to adequately fit discard compositions from the Non-Trawl fleet (**Figure XX**). The Non-Trawl discards were of a larger size and were generally more dispersed than the discard compositions in the two trawl fleets, a feature the model did pick up on, but the model fitted a wide plateau rather than narrow peak to these composition data. This is likely due to the wide variability in annual length compositions seen in this fleet, as well as the wide spatial coverage.

#### Survey Length Compositions
Like the fishery derived length compositions, survey-derived length compositions were reasonably well fit in aggregate by the base model, though there was considerable annual variability in the quality of the model fit (**Figure XX**). The early-period Triennial survey length composition data for both sexes were exceptionally well fit by the model. Length compositions from the late-period Triennial survey were slightly less well fit, with the model under-estimating the location of the peak for both sexes. For the \gls{s-wcgbt} length compositions, the male, female, and unsexed location of the compositional peaks were well estimated, though the overall scales were slightly underestimated. Pearson residuals did not demonstrate any obvious trends that would indicate systematic misfits to the data (**Figure XX**); as such, time varying selectivity was not included in the base model. 

#### Mean Body Weight 
Mean body weight of discarded fish was well fit in the two trawl fleets, and no major trends were observed in either the data of the model estimates. Mean discard weight in the Non-Trawl fleet was observed to have increased in the last ten years, but this trend was not captured by the model. The model, instead, fit a declining trend in discard weight to the Non-Trawl fleet data. The reason for this disparity between the observed data and the model fit is unclear.

### Population Trajectory
Unfished equilibrium spawning output (B0) is estimated to be 20,262 eggs, with a 95% confidence interval of 16,291–24,232 eggs. The B0 estimate is not directly comparable to estimates made in previous assessments, which assumed no fecundity relationship, and thus calculated B0 in terms of biomass rather than egg production. Spawning biomass is estimated to have remained stable until the mid-1960s and then declined in the 1970s to about 80% in the mid-1980s, followed by a slower decline under the lower catch levels in the 2000s (**Table XX**, **Figure XX**). While the spawning output of the stock has declined near linearly since 1975, total biomass has stabilized in recent decades around ~85,000 mt.  The estimated spawning output  in 2023 is **8,204 eggs**, which represents a stock status or “depletion” of 40% (**Figure XX**). The depletion estimated for 2013 is 43.5%, which is significantly lower than the 74.2% estimated for 2013 in the previous assessment. 

Twelve-year projections predict that the population is unlikely to experience a large increase in spawning output or spawning biomass in the near future, if the full \gls{acl} is taken each year (**Figure XX**).

### Reference Points

Reference points were calculated using the estimated catch distribution in the final year of the model (2023). In general, the population is on the boundary between “precautionary” (B/B0 = 0.40) and “healthy” status relative to the reference points (Figure XX). Sustainable total yield (landings plus discards) was estimated at 1,060 mt when using an SPR50% reference harvest rate and ranged from 870–1,250 mt based on estimates of uncertainty (Table XX). The spawning output equivalent to 40% of the unfished spawning output (B40%) was **8,105 eggs**.  
**The most recent catches (landings plus discards) have been lower than the estimated long-term yields calculated using an SPR50% reference point, but not as low as the lower bound of the 95% uncertainty interval. However, this is due to the fishery not fully attaining the full ACL. The \gls{ofl} and \gls{acl} values over the past 6 years have been approximately 2,400 mt and 2,000 mt, respectively.**

Both of those values are higher than the \gls{ofl} and \gls{acl} values predicted in short-term forecasts, which are around **853 mt and 420 mt** respectively for 2023–2024 (**Table XX**). This is reflected in the timeseries of low harvest rates (**Figure XX**), low 1-SPR values (**Figure XX**), and the phase plot showing the history of being above the target biomass and below the target fishing intensity reference points (**Figure XX**).
