## Model Diagnostics

### Convergence
The maximum likelihood parameter estimates found by \gls{admb} indicated a well-converged model. The base model had a small maximum gradient component (0.0002317) and a positive definite Hessian matrix, both of which are associated with converged models.

Runs with 100 alternative sets of starting parameter values found no models with a better likelihood (**Table JITTER RESULTS**). Of the 100 jittered model runs, 74 reconverged to the best estimates associated with the base model, while 76 reconverged to within 0.25% of the best estimate. This indicates that the data is relatively informative about the population dynamics of the stock, as the model fits to the data were virtually identical.

### Sensitivity Analyses
#### Sensitivity to growth parameters
Growth parameters are uncertain for `r spp` due to difficulties in determining age from otoliths and subsequent lack of length-at-age information for this species, thus, sensitivities of length-at-age 25% higher and 10% lower was conducted to encompass the uncertainty in growth. Different assumptions about growth did not have much influence on relative spawning depletion. Depletion levels in the final year were slightly greater in a higher growth scenario and slightly lower in a lower growth scenario (Figure \ref{fig:growth_sensitiv_mngmt}). Spawning output was more sensitive to assumptions about growth, with much higher spawning output when assuming a higher growth scenario (Figure \ref{fig:growth_sensitiv_spawning}). The high growth sensitivity had a slightly better overall fit to the data, including to the survey indices and length compositions (Table \ref{tab:sentivititytab}). Different assumptions about growth influence recruitment patterns and the timing of strong year classes. However, the influence of different growth assumptions is also sensitive to changes in other parameters, such as natural mortality.

#### Sensitivity to maturity
The 2023 assessment uses updated maturity-at-length information from the \gls{s-wcgbt} and port-sampling (Melissa Head, pers. comms.), which show a larger length at 50% maturity (31.4 cm) and shallower slope (-0.177) of a logistic regression compared to a smaller length at 50% maturity (18.1 cm) and steeper slope (-2.304) assumed in the 2013 assessment based on @pearson_gunderson_2003. A sensitivity was conducted to maturity information from the two datasets and to an intermediate maturity-at-length logistic curve (mix_curve, $L_{50\%}$ = 24.8 cm and slope = -0.350). As in the 2013 assessment, the base model was not sensitive to different maturity assumptions (Figure \ref{fig:mat_sensitiv_spawning}; Figure \ref{fig:mat_sensitiv_mngmt}). Differences in fits to the data were negligible. The slightly higher stock status in the final year with the @pearson_gunderson_2003 maturity assumptions is likely due to females from strong cohorts in the 2000s being (or becoming) mature that are not yet mature with 2023 larger size-at-maturity assumptions. As stated in the 2013 assessment, the slow but steady rate of growth for `r spp`, with growth still occurring at age 100, reduces the importance of assumptions about maturity because older individuals will have significantly higher spawning output due to their much larger size, regardless of the fraction spawning. 

#### Sensitivity to Landings
Two sensitivities were conducted to explore how changes in the historical landings timeseries effect modern-day estimates of stock status. One sensitivity replaces the historical landings reconstructions prior to 1962 with the imputed landings that were used in the 2005 and 2013 assessments. A second sensitivity replaces all landings information prior to 2013 with the values that were used in the 2013 assessment. There was little appreciable difference to base model fits across the two sensitivities (Figure \ref{fig:land_sensitiv_spawning}; Figure \ref{fig:land_sensitiv_mngmt}). This is likely due to the fact that historical catches (pre-1962), and changes in catches due to state-level catch reconstruction updates, were relatively small and thus would have had minimal impact of the biomass timeseries. 

#### Sensitivity to retention and selectivity
The 2023 assessment substantially extends the period over both length data of retained and discarded catch, mean individual weight in discards and discard rates estimates are available. This data may reflect the dynamics of the thornyhead of the population but also structural, technical or behavioral changes in the fishing fleets. Due to the uncertainty around the impact of such changes on the retention and selectivity of the fleets, we assessed the sensitivity of the model to alternative combinations of time blocks for these parameters. The sensitivity to time blocks in retention was first performed and the most pertinent model (good fit to the data and parsimony) and the base model were then used to conduct the sensitivity to time blocks in selectivity. Time blocks explored were based on a combination of breaks that are summarized in **Table XX**.

Setting up additional time blocks for the retention parameters improved the fit of the model to the length distributions and the discard rates, hence reducing corresponding likelihood of the model. However, the impact on the other components of the model likelihood were very limited. None of the time blocks tested substantially reduced other components of the model likelihood or led to changes in the recruitment trends or the depletion status of the population (**Figure XX**).  


### Retrospective Analysis
Retrospective analysis indicates that removing the most recent years of data has minimal impact on the estimates of spawning output (Figure \ref{fig:retros_spawnbio}) and stock status (Figure \ref{fig:retros_bratio}). This is consistent with the results of the likelihood profile over $R_0$ (Figure \ref{fig:R0_prof})) which showed that the data are moderately informative about stock scale. While the analysis does display some very minimal evidence of a retrospective pattern, all estimates of spawning output in the retrospective analysis fell within the 95% uncertainty interval around the base model spawning output time series (Figure \ref{fig:retros_spawnbio_uncertainty}).

As in the previous assessment, there is little evidence that such retrospective patterns are the result of additional years of survey abundance data (Figure \ref{fig:retros_indices}), and thus, it is most likely that removal of informative length composition data is the source of such pattern.

### Likelihood Profiles
Likelihood profiles were conducted over the log of unfished recruitment ($R_0$), the steepness of the stock recruit relationship ($h$), the value of natural mortality ($M$), and the growth curve. 

A likelihood profile over $\ln(R_0)$ was performed to assess the influence of the various data sources on the unfished scale of the population. The profile shows most of the data sources to be in agreement regarding the best estimate of $R_0$, with the exception of the indices of abundance, which are best fit by larger values of $R_0$ (Figure \ref{fig:R0_prof}). Similarly, there is little inconsistency in likelihood contribution by fleet across the range of plausible $R_0$ values (Figure \ref{fig:R0_prof}). This indicates that the data, together, are relatively informative about the overall scale of the population. The highest spawning output and lowest depletion levels were associated with higher $R_0$ values (Figure \ref{fig:R0_spawnout}).

Likelihood values and model results were largely insensitive to changes in steepness (Figure \ref{fig:h_piner_prof}). The change in negative log likelihood over the range of $h = 0.5–1.0$ was less than 10 units with the largest contribution coming from recruitment and abundance indices. No other likelihood component had a change of greater than 1 unit. The lowest $B_0$ and depletion values were associated with the most productive population, with $h = 1.0$, but there was no qualitative difference between any of these cases (total change in depletion values across the range of $h$ tested was 0.02 units; Figure \ref{fig:h_spawnout}). The apparent lack of influence of h on population dynamics for `r spp` is likely the result of the relatively high estimated stock status across the entire time series, which makes estimation of h difficult. 

A likelihood profile over natural mortality ($M$) found the model results to be quite sensitive to the assumed value of $M$: with all values of $M$ 0.03-0.05 resulting in likelihoods within 1 unit of the base model (Figure \ref{fig:M_prof}). Meanwhile there was no support in the data for values of $M$ above 0.06. Length composition data, particularly from the two trawl fleets, was the major contributor to the changes in likelihood observed over the range of tested values for $M$ (Figure \ref{fig:M_prof}). All plausible values of $M$ resulted in similar levels of depletion (Figure \ref{fig:M_relspawnout}), but a wide range of levels for unfished spawning output (Figure \ref{fig:M_spawnout})

Because of the high sensitivity of the model to assumptions about growth, a likelihood profile over growth coefficients, length at minimum age ($a_{min}$) and length at maximum age ($a_{max}$), for each sex, was conducted. For the profile, length at amin for females ranged from 10 cm to 15 cm and length at a_{max} ranged from 60 cm to 150 cm. For males, length at $a_{min}$ ranged from 8cm to 12 cm and length at $a_{max}$ ranged from 55 cm to 140 cm. As with the growth sensitivity analysis described above, likelihood was minimized for higher growth scenarios (Figure \ref{fig:growth_prof}). Spawning biomass trajectories showed similar patterns to the growth sensitivity, with higher growth scenarios producing substantially higher spawning output (Figure \ref{fig:growth_spawnout}). Based on both the fishery and survey length compositions, the largest fish, under a high growth model, are not necessarily being observed in the data. This, in combination with a low natural mortality, may be driving the higher spawning output patterns under high growth scenarios.  

### Unresolved Problems and Major Uncertainties
Few problems remain totally unresolved, though improvements to the model fit to the \gls{s-wcgbt} abundance indices and to the North Trawl fleet length compositions would be desirable. In addition, being able to freely estimate the width of the selectivity plateaus for many of the fleets and surveys would also improve the model. 

The model fails, at this time, to fully capture the observed increase in abundance seen in the \gls{s-wcgbt} index time series, significantly underestimating the abundance in 2021 and 2022 (Figure \ref{fig:fitscombo}). Better fits to \gls{s-wcgbt} length compositions in those years could possibly improve fits to the indices, but improvements to the length composition fits proved difficult without introducing time-blocked selectivity. As the \gls{s-wcgbt} is supposed to follow highly standardized survey methodologies, there seems to be minimal justification for introducing time-varying selectivity in the model at this time. The model also fails to fully capture the peak of the length compositions for the Northern Trawl fleet, underestimating the number of mid-sized fish that the fleet takes (Figure \ref{fig:lencomps_all}). This underestimation appears to be consistent, particularly in the last 10 years (Figure \ref{fig:ntrawl_comps_ten}), implying a possible recent change in selectivity. While time-varying selectivity was not investigated here, if this trend persists, future assessments may wish to apply a selectivity time block to this fleet in order to better capture the peaks of the length compositions.

Major uncertainties in the model are centered around uncertainty in the biological parameters that govern growth, maturity, and mortality. Due to a lack of reliable aging methods, growth was estimated externally to data collected in the 1990s (see **section 2.3.4** for more information). Sensitivities conducted on the length-at-age-100 demonstrated that changes to the growth function could have large effects on the estimated stock status (Figure \ref{fig:growth_sensitiv_mngmt}). Due to inconsistent histological data for `r spp`, there is some uncertainty about the shape of the species’ maturity curve, though the model appears to be largely insensitive to variations in maturity (Figure \ref{fig:mat_sensitiv_mngmt}). Finally, likelihood profiles over natural mortality demonstrate the model to be quite sensitive to its assumed value. There is insufficient information in the data to estimate mortality directly, constraining us to using meta-analyses or other mortality estimators, which frequently make use of aging information that is unavailable or highly uncertain for `r spp`.
