# Management 

## Reference Points
Reference points were calculated using the estimated catch distribution in the final year of the model (2023). In general, the population is on the boundary between “precautionary” ($B/B_0 = 0.40$) and “healthy” status relative to the reference points (Figure \ref{fig:relspawnout}). Sustainable total yield (landings plus discards) was estimated at 1,108 mt when using an $SPR_{50\%}$ reference harvest rate and ranged from 929-1,288 mt based on estimates of uncertainty (Table \ref{tab:refPoints}). The spawning output equivalent to 40% of the unfished spawning output ($B_{40\%}$) was 8.858 billion eggs.  The most recent catches (landings plus discards) have been lower than the estimated long-term yields calculated using an $SPR_{50\%}$ reference point, but not as low as the lower bound of the 95% uncertainty interval. However, this is due to the fishery not fully attaining the full \gls{acl}. The \gls{ofl} and \gls{abc} values over the past 6 years have been approximately 3100 mt and 2,500 mt, respectively. Both of those values are higher than the \gls{ofl} and \gls{acl} values predicted in short-term forecasts, which are around 900 mt and 700 mt respectively for 2025–2026 (Table \ref{tab:projections}). This is reflected in the timeseries of low harvest rates (Figure \ref{fig:summary_f}), high 1-SPR values (Figure \ref{fig:spr_trajectory}), and the phase plot showing the history of being above the target biomass but also above the target fishing intensity reference points (Figure \ref{fig:phase_diagram}). The sharp decline in the \gls{ofl} and \gls{acl} in coming years is the result of continued decline in the relative spawning output of the stock, which has placed it very near the “precautionary” zone for management.

## Harvest Projections and Decision Tables
The standard deviation of the log of spawning biomass in 2023 is $\sigma = 0.18$. This value is in the adjustment of quotas based on scientific uncertainty (a process referred to by the notation “$P^*$”) when the value is greater than an assumed 0.36 minimum, as it is in this case. The associated offset would therefore be a multiplication of the OFL by 76.2%, which is the 40% quantile of a log-normal distribution with the associated $\sigma$. Twelve-year projections were conducted with a total catch assumed equal to the ACL calculated by applying this adjustment to the estimated OFL for each year. The selectivity and retention function and allocation of catch among fleets was assumed to match the values for the 2020-2022 timeblock. Catch for 2023 and 2024, the limits on which have already been set, were provided by the \gls{pfmc}, and correspond to a total catch of 756 mt.

This default harvest projection applied to the base model indicated that the stock status would slowly decline from 39.4% in 2023 to 39.2% in 2024, before beginning a slow rebound to 40.1% by 2034. The associated OFL values over the period 2025–2034 would average 1,022 mt and the average ACL would be 718 mt. These values are near recent annual catch levels.

Additional projections were conducted for the base model and low and high states of nature (columns) under two catch streams (rows) representing different levels of scientific uncertainty, and thus different values of $P^*$. The uncertainty in the \gls{ofl} associated with the base model was broad ($\sigma = 0.18$), and states of nature were chosen based on values of natural mortality (M) that encapsulated the range of M seen in the literature. The low state of nature used $M=0.03$ to fully encapsulate the low end of the range of M seen in assessments throughout the eastern Pacific. The high state of nature used M=0.05 to roughly encapsulate the value of M used by the 2013 assessment. 

The catch streams chosen for the decision table were represented as total catch rather than landed catch, but discard rates were low under IFQs, so the difference in between total catch and landings is small, and represent catch under two distinct levels of $P^*$ ($P^*=0.40$ and $P^*=0.45$). The most pessimistic forecast scenario, combining the low state of nature (M=0.03) with the high catch stream (P*=0.45), resulted in a projected stock status of 38.7%, very close to the target value. All other projections led to a higher projected status, with a maximum of 54.7% for the combination of the high state of nature and low catch. Forecasts under the base case led to estimated status ranging from 2024 spawning depletion values of 39.1% in both catch scenarios.

A decision table (Table \ref{tab:decisiontable}) was assembled using projections associated with the high and low states of nature (columns) under two catch streams (rows).

## Evaluation of Scientific Uncertainty
Scientific uncertainty was evaluated via several likelihood profiles and a wide range of sensitivity analyses, not all of which are reported on here. Likelihood profiles were performed over unfished recruitment ($R_0$), recruitment steepness ($h$), and natural mortality ($M$), as required by the Groundfish Terms of Reference. The profiles found the model results, particularly estimates of stock scale, to be relatively sensitive to changes to $R_0$ and M, as would be expected, but largely insensitive to changes in steepness. An additional likelihood profile was also run over growth, and found the model results to be quite sensitive to the assumed values of the growth curve. Sensitivities were performed using alternative growth and maturity curves, alternative time blocks for selectivity and retention, and alternative historical landings timeseries. Model results (particularly estimates of stock status) were largely insensitive to all changes except for growth.

The model estimated uncertainty around the 2023 spawning biomass was $\sigma = 0.18$ and the uncertainty around the \gls{ofl} was $\sigma = 0.16$.


## Research and Data Needs
Research and data needs for future assessments include the following: 

1. Research into aging methods and availability of reliable age data would be valuable for future stock assessments. Otoliths have been collected in good quantities from the NWFSC survey, but there is currently no validated aging method for `r spp`. 
2. Additional investigation into growth patterns would provide valuable information for future population projections. We acknowledge that additional work on aging `r spp` would be required to make such additional growth research possible.
3. More investigation into maturity of `r spp` is necessary to understand the patterns in maturity observed in \gls{s-wcgbt} samples. 
4. Information on possible migration of `r spp`s would be valuable for understanding stock dynamics. Analysis of trace elements and stable isotopes in shortspine otoliths may provide valuable information on the extent of potential migrations. Possible connections between migration and maturity could likewise be explored. 
5. A greater understanding of the connection between thornyheads and bottom type could be used to refine the indices of abundance. Thornyheads are very well sampled in trawlable habitat, but the extrapolation of density to a survey stratum could be improved by accounting for the proportion of different bottom types within a stratum and the relative density of thornyheads within each bottom type.
6. Additional investigation into spatial stock structure could be valuable for determining whether future assessments should develop a spatial assessment model, or if `r spp` should be assessed at distinct spatial scales in the future.
7. Further research into the Dirichilet-Multinmoial (DMN) data-weighting method for length-composition data is needed for integration with length-based data-moderate assessments like `r spp`. The DMN method has not, to date, been thoroughly simulation tested with length-composition data, and an attempted sensitivity analysis performed for the 2023 assessment failed to converge entirely. This is a general research need, and is widely applicable to many data-moderate or length-based assessments, not just `r spp`.

